apiVersion: v1
kind: Service
metadata:
  name: cloudwebapplication-service
spec:
  selector:
    app: cloudwebapplication
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer