name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1

    - name: Login to ECR (Manual Method)
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 988732826295.dkr.ecr.us-east-1.amazonaws.com

    - name: Build and tag Docker image
      run: |
        docker build -t cloudsync-webapp -f CloudWebApplication/Dockerfile .
        docker tag cloudsync-webapp:latest 988732826295.dkr.ecr.us-east-1.amazonaws.com/cloudsync/webapp:latest

    - name: Push to ECR
      run: docker push 988732826295.dkr.ecr.us-east-1.amazonaws.com/cloudsync/webapp:latest
